uuidGenerator:
  handler: functions/uuidGenerator/uuidGenerator.handler
  package:
    individually: true
    exclude:
      - "./**"
    include:
      - ./functions/uuidGenerator/uuidGenerator.js
      - ./functions/uuidGenerator/node_modules/**
      - ./functions/uuidGenerator/package.json
